const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict'),net=require('net'),{spawn}=require('child_process');
// 非规范文件名与 !important 属性预览回归，所有源文件只读。
const base=path.resolve(__dirname,'..');const root=fs.mkdtempSync('/tmp/ycet-name-check-');fs.mkdirSync(root+'/prototype/outputs',{recursive:true});
const plain=important=>`<!doctype html><html><head><meta charset="utf-8"><style>#sample{font-size:16px${important?' !important':''};width:160px;height:64px}</style></head><body><button id="sample">测试按钮</button></body></html>`;
const cases=[['prototype-pages.html',plain(false)],['我的测试页面.html',plain(false)],['arbitrary-important.html',plain(true)]];
for(const [name,html]of cases)fs.writeFileSync(root+'/prototype/outputs/'+name,html);
(async()=>{const port=await new Promise(r=>{let s=net.createServer();s.listen(0,'127.0.0.1',()=>{let p=s.address().port;s.close(()=>r(p))})});const token='diagnostic-test';const url='http://127.0.0.1:'+port;const server=spawn(process.env.PYTHON||'python3',[base+'/scripts/prototype_workbench.py','serve','--project-root',root,'--port',String(port),'--token',token],{stdio:'ignore',env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'}});let browser;const results=[];
try{for(let i=0;i<60;i++){try{if((await fetch(url+'/api/health',{headers:{'X-YCET-Token':token}})).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
browser=await chromium.launch({channel:'chrome',headless:true});
for(const [name]of cases){const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url+'/?token='+token);await page.locator('.file-row').filter({hasText:name}).click();const frame=page.frameLocator('#preview-frame');await frame.locator('#sample').waitFor();await page.locator('#select-mode').click();await frame.locator('#sample').click();await page.waitForFunction(()=>document.querySelector('#selected-name').textContent==='button#sample');await page.locator('#font-size').fill('23');await page.locator('#font-size').press('Tab');await page.waitForTimeout(300);const actual=await frame.locator('#sample').evaluate(e=>({computed:getComputedStyle(e).fontSize,inline:e.style.fontSize}));assert.equal(actual.computed,'23px');await page.locator('#undo-changes').click();await page.waitForTimeout(150);assert.equal(await frame.locator('#sample').evaluate(e=>getComputedStyle(e).fontSize),'16px');assert.equal(await frame.locator('#sample').getAttribute('style'),null);results.push({name,...actual,errors,sourceUnchanged:fs.readFileSync(root+'/prototype/outputs/'+name,'utf8')===cases.find(c=>c[0]===name)[1]});await page.close();}
console.log(JSON.stringify(results,null,2));fs.writeFileSync('/tmp/ycet-name-preview-results.json',JSON.stringify(results,null,2));
assert.equal(results[0].computed,'23px');assert.equal(results[1].computed,'23px');assert(results.every(r=>r.sourceUnchanged&&r.errors.length===0));
}finally{if(browser)await browser.close();server.kill('SIGTERM');}
})().catch(e=>{console.error(e);process.exitCode=1});
