// 临时工作台端到端回归，不启动用户项目工作台。
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),net=require('node:net'),crypto=require('node:crypto'),{spawn}=require('node:child_process');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{const root=path.resolve(process.argv[2]);const port=await new Promise(r=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>r(p))})});const token='v4-local-test';const url='http://127.0.0.1:'+port;
const server=spawn(process.env.PYTHON||'python3',[path.join(__dirname,'prototype_workbench.py'),'serve','--project-root',root,'--port',String(port),'--token',token],{env:{...process.env,PYTHONDONTWRITEBYTECODE:'1'},stdio:'ignore'});let browser;
const api=async(p,body)=>{const res=await fetch(url+p,{method:body?'POST':'GET',headers:{'X-YCET-Token':token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!res.ok)throw Error('HTTP '+res.status+' '+p);return res.json()};
try{let ready=false;for(let i=0;i<60;i++){try{await api('/api/health');ready=true;break}catch(e){await delay(100)}}assert(ready,'server not ready');
browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const source=path.join(root,'prototype/outputs/prototype-pages.html');const before=fs.readFileSync(source);await page.goto(url+'/?token='+token);await page.waitForSelector('.file-row');assert.equal(await page.locator('#sync-pages').count(),0);
await page.locator('.file-row').filter({hasText:'prototype-pages.html'}).click();const preview=page.frameLocator('#preview-frame');await preview.locator('[data-ycet-page-id=home]').waitFor();await page.evaluate(()=>{window.testSelections=[];window.addEventListener('message',e=>{if(e.data?.type==='selection')window.testSelections.push(e.data)})});await page.locator('#select-mode').click();await preview.locator('[data-ycet-page-id=home] [data-ycet-element-id=count]').click();await page.waitForFunction(()=>document.querySelector('#selected-name').textContent==='button');await page.waitForTimeout(200);await page.locator('#font-size').fill('23');await page.locator('#font-size').press('Tab');await page.waitForTimeout(500);assert.equal(await preview.locator('[data-ycet-page-id=home] [data-ycet-element-id=count]').evaluate(e=>getComputedStyle(e).fontSize),'23px');assert.notEqual(await preview.locator('[data-ycet-page-id=detail] [data-ycet-element-id=count]').evaluate(e=>getComputedStyle(e).fontSize),'23px');
await page.locator('#undo-changes').click();await page.waitForTimeout(150);assert.notEqual(await preview.locator('[data-ycet-page-id=home] [data-ycet-element-id=count]').evaluate(e=>getComputedStyle(e).fontSize),'23px');
await page.locator('#font-size').fill('24');await page.locator('#font-size').press('Tab');await page.locator('#send-ai').click();await page.waitForTimeout(250);const listing=await api('/api/requests');assert(!('syncPages' in listing));const dir=path.join(root,'.ycet-editor/requests');const packages=fs.readdirSync(dir).filter(f=>f.endsWith('.json')&&!f.includes('.state.')&&!f.includes('.result.')).map(f=>JSON.parse(fs.readFileSync(path.join(dir,f))));const pkg=packages.at(-1);assert(pkg);assert.equal(pkg.files.length,1);assert.equal(pkg.files[0].operations[0].priority,'important');assert.equal(pkg.files[0].operations[0].fingerprint.pageId,'home');assert.equal(pkg.files[0].operations[0].fingerprint.elementId,'count');assert.equal(Buffer.compare(before,fs.readFileSync(source)),0);assert(!fs.readdirSync(path.dirname(source)).some(f=>/-v\d/.test(f)));assert.deepEqual(errors,[]);await page.screenshot({path:path.join(root,'workbench-v4.png')});console.log('PASS: 工作台扫描、同文件多页定位、样式草稿、撤回、请求指纹、源文件保护、同步移除');
}finally{if(browser)await browser.close();try{await api('/api/shutdown',{})}catch(e){}server.kill('SIGTERM');}
})().catch(e=>{console.error(e);process.exitCode=1});
